version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_chat_prod

  web:
    image: horizon0708/graphql_chat:latest
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - HOST=http://192.168.99.100
    links:
      - db:db
